### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by santi224m** [santi224m/filey#15]
There is a typo on the [about page](https://filey-app.com/about)

![image](https://user-images.githubusercontent.com/36117697/114639141-fc261300-9c81-11eb-9d48-e7bb1024dae8.png)

 It should say ```your code```

**Comment by DineshKoushik** [comment]
Hi @santi224m , can you check the PR?

**Comment by santi224m** [comment]
@DineshKoushik It looks good, thank you
